import config
from  models import *
import json
import os 
con = config.Config()
con.set_in_path("./benchmarks/FB15K237/")
con.set_rdict_path("./benchmarks/fb_miss_dict.pkl")
con.set_premodel_path("./result/QuatE_fb.ckpt")
con.set_hdict_path("./benchmarks/fbh_rel_dict.pkl")
con.set_tdict_path("./benchmarks/fbt_rel_dict.pkl")
con.set_pot_mode("a")
con.set_filter_lmbda(0.5)
con.set_work_threads(8)
con.set_train_times(10000)
con.set_nextStage(5000)
con.set_nbatches(10)
con.set_alpha(0.02)
con.set_bern(1)
con.set_dimension(100)
con.set_lmbda(0.1)
con.set_lmbda_two(0.1)
con.set_margin(1.0)
con.set_ent_neg_rate(10)
con.set_rel_neg_rate(0)
con.set_opt_method("adagrad")
con.set_save_steps(8000)
con.set_valid_steps(8000)
con.set_early_stopping_patience(10)
con.set_checkpoint_dir("./checkpoint")
con.set_result_dir("./result_fb")
con.set_test_link(True)
con.set_test_triple(True)
con.init()
con.set_train_model(PreQuatE)
con.train()
