import config
from  models import *
import json
import os 
con = config.Config()
con.set_in_path("./benchmarks/NELL-995/")
con.set_rdict_path("./benchmarks/nl_miss_dict.pkl")
con.set_premodel_path("./result/QuatE_nl.ckpt")
con.set_hdict_path("./benchmarks/nlh_rel_dict.pkl")
con.set_tdict_path("./benchmarks/nlt_rel_dict.pkl")
con.set_work_threads(8)
con.set_pot_mode("h")
con.set_filter_lmbda(0.5)
con.set_train_times(10000)
con.set_nextStage(5000)
con.set_nbatches(10)
con.set_alpha(0.1)
con.set_bern(1)
con.set_dimension(200)
con.set_lmbda(0.3)
con.set_lmbda_two(0.1)
con.set_margin(1.0)
con.set_ent_neg_rate(10)
con.set_rel_neg_rate(0)
con.set_opt_method("adagrad")
con.set_save_steps(8000)
con.set_valid_steps(8000)
con.set_early_stopping_patience(10)
con.set_checkpoint_dir("./checkpoint")
con.set_result_dir("./result_nl")
con.set_test_link(True)
con.set_test_triple(True)
con.init()
con.set_train_model(PreQuatE)
con.train()
